import { useCallback, useEffect, useState } from "react";
import { Edit3, Plus, Save, X } from "lucide-react";
import { useAuth } from "../context/AuthContext";

const API_BASE = "http://localhost:5000/api";
const currencyOptions = ["INR", "USD", "EUR", "GBP"];
const frequencies = ["MONTHLY", "QUARTERLY", "YEARLY"];
const EMPTY_PLAN = { name: "", billingFrequency: "MONTHLY", discountIncentive: 0, status: "ACTIVE" };

function apiError(data, fallback) { return data.message || fallback; }

export default function AdminGovernance({ mode }) {
  const { token } = useAuth();
  const [records, setRecords] = useState([]);
  const [config, setConfig] = useState({ currency: "INR", invoicePrefix: "INV-", paymentTerms: "NET_30", taxEnabled: true, defaultTaxRate: 18, invoiceDuePeriod: 30 });
  const [plan, setPlan] = useState(EMPTY_PLAN);
  const [editingPlan, setEditingPlan] = useState(null);
  const [editingTier, setEditingTier] = useState(null);
  const [filters, setFilters] = useState({ search: "", action: "", from: "", to: "" });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const request = async (path, options = {}) => {
    const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...(options.headers || {}) } });
    const data = await response.json();
    if (!response.ok) throw new Error(apiError(data, "Request failed."));
    return data;
  };

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      if (mode === "audit") setRecords((await request(`/admin/audit-logs?${new URLSearchParams(filters)}`)).data || []);
      if (mode === "billing") { const data = (await request("/admin/billing-configuration")).data; if (data) setConfig(data); }
      if (mode === "plans") setRecords((await request("/admin/subscription-plans")).data || []);
      if (mode === "tiers") setRecords((await request("/admin/customer-tiers")).data || []);
    } catch (requestError) { setError(requestError.message); } finally { setLoading(false); }
  }, [mode, token]);

  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, [load]);

  const saveBilling = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const data = await request("/admin/billing-configuration", { method: "PUT", body: JSON.stringify(config) }); setConfig(data.data); setSuccess(data.message); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const savePlan = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const data = await request(`/admin/subscription-plans${editingPlan ? `/${editingPlan.id}` : ""}`, { method: editingPlan ? "PUT" : "POST", body: JSON.stringify({ ...plan, discountIncentive: Number(plan.discountIncentive) }) }); setSuccess(data.message); setEditingPlan(null); setPlan(EMPTY_PLAN); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const saveTier = async (tier) => { setSaving(true); setError(""); try { const data = await request(`/admin/customer-tiers/${tier.id}`, { method: "PUT", body: JSON.stringify({ description: tier.description, status: tier.status }) }); setSuccess(data.message); setEditingTier(null); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };

  const heading = { audit: ["Audit Logs", "Review real system actions and changes."], billing: ["Billing Configuration", "Configure defaults used by the billing and invoice flow."], plans: ["Subscription Plans", "Manage plans used by recurring deals and billing."], tiers: ["Customer Tiers", "Manage the fixed customer tiers used by discount policies and risk rules."] }[mode];
  return <main className="main-content admin-page"><div className="page-heading-row"><div><p className="eyebrow">Admin governance</p><h1>{heading[0]}</h1><p className="page-subtitle">{heading[1]}</p></div></div>{error && <div className="alert alert-danger">{error}</div>}{success && <div className="alert alert-success">{success}</div>}
    {mode === "audit" && <section className="admin-panel governance-panel"><div className="governance-filters"><input className="form-input no-icon" placeholder="Search audit logs..." value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /><select className="form-select no-icon" value={filters.action} onChange={(e) => setFilters({ ...filters, action: e.target.value })}><option value="">All Actions</option><option value="CREATED">Created</option><option value="UPDATED">Updated</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option><option value="DISABLED">Disabled</option></select><input className="form-input no-icon" type="date" value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value })} /><input className="form-input no-icon" type="date" value={filters.to} onChange={(e) => setFilters({ ...filters, to: e.target.value })} /><button className="btn-primary" onClick={load}>Filter</button></div><div className="governance-table-wrap"><table className="data-table"><thead><tr><th>Date & Time</th><th>User</th><th>Activity</th><th>Action</th><th>Details</th></tr></thead><tbody>{loading ? <tr><td colSpan="5" className="empty-state">Loading audit logs...</td></tr> : records.length === 0 ? <tr><td colSpan="5" className="empty-state">No audit events found.</td></tr> : records.map((log) => <tr key={log.id}><td>{new Date(log.createdAt).toLocaleString("en-IN")}</td><td>{log.user?.name || "System"}</td><td>{log.action.replaceAll("_", " ")}</td><td><span className="badge badge-active">{log.action.split("_").pop()}</span></td><td><code>{JSON.stringify(log.details)}</code></td></tr>)}</tbody></table></div></section>}
    {mode === "billing" && <form className="admin-panel governance-form" onSubmit={saveBilling}><div className="form-row"><label className="form-group"><span className="form-label">Default Currency</span><select className="form-select no-icon" value={config.currency} onChange={(e) => setConfig({ ...config, currency: e.target.value })}>{currencyOptions.map((item) => <option key={item}>{item}</option>)}</select></label><label className="form-group"><span className="form-label">Invoice Prefix</span><input className="form-input no-icon" value={config.invoicePrefix} onChange={(e) => setConfig({ ...config, invoicePrefix: e.target.value })} required /></label></div><div className="form-row"><label className="form-group"><span className="form-label">Payment Terms</span><select className="form-select no-icon" value={config.paymentTerms} onChange={(e) => setConfig({ ...config, paymentTerms: e.target.value })}>{[["DUE_ON_RECEIPT", "Due on Receipt"], ["NET_15", "Net 15"], ["NET_30", "Net 30"], ["NET_45", "Net 45"], ["NET_60", "Net 60"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="form-group"><span className="form-label">Invoice Due Period (days)</span><input className="form-input no-icon" type="number" min="0" value={config.invoiceDuePeriod} onChange={(e) => setConfig({ ...config, invoiceDuePeriod: e.target.value })} required /></label></div><label className="governance-checkbox"><input type="checkbox" checked={config.taxEnabled} onChange={(e) => setConfig({ ...config, taxEnabled: e.target.checked })} /> Tax / GST enabled</label>{config.taxEnabled && <label className="form-group"><span className="form-label">Default Tax Rate (%)</span><input className="form-input no-icon" type="number" min="0" max="100" step="0.01" value={config.defaultTaxRate} onChange={(e) => setConfig({ ...config, defaultTaxRate: e.target.value })} required /></label>}<button className="btn-primary" disabled={saving}><Save size={16} /> Save Configuration</button></form>}
    {mode === "plans" && <><section className="admin-panel governance-form"><form onSubmit={savePlan}><div className="form-row"><label className="form-group"><span className="form-label">Plan Name</span><input className="form-input no-icon" value={plan.name} onChange={(e) => setPlan({ ...plan, name: e.target.value })} required /></label><label className="form-group"><span className="form-label">Billing Frequency</span><select className="form-select no-icon" value={plan.billingFrequency} onChange={(e) => setPlan({ ...plan, billingFrequency: e.target.value })}>{frequencies.map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="form-row"><label className="form-group"><span className="form-label">Discount Incentive (%)</span><input className="form-input no-icon" type="number" min="0" max="100" value={plan.discountIncentive} onChange={(e) => setPlan({ ...plan, discountIncentive: e.target.value })} required /></label><label className="form-group"><span className="form-label">Status</span><select className="form-select no-icon" value={plan.status} onChange={(e) => setPlan({ ...plan, status: e.target.value })}><option>ACTIVE</option><option>INACTIVE</option></select></label></div><div className="form-actions">{editingPlan && <button type="button" className="btn-secondary" onClick={() => { setEditingPlan(null); setPlan(EMPTY_PLAN); }}><X size={15} /> Cancel</button>}<button className="btn-primary"><Plus size={16} /> {editingPlan ? "Save changes" : "Add Subscription Plan"}</button></div></form></section><section className="admin-panel governance-table-wrap"><table className="data-table"><thead><tr><th>Plan</th><th>Frequency</th><th>Discount</th><th>Status</th><th /></tr></thead><tbody>{records.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.billingFrequency}</td><td>{item.discountIncentive}%</td><td>{item.status}</td><td><button className="icon-button" onClick={() => { setEditingPlan(item); setPlan(item); }}><Edit3 size={16} /></button></td></tr>)}</tbody></table></section></>}
    {mode === "tiers" && <section className="admin-panel governance-table-wrap"><table className="data-table"><thead><tr><th>Tier</th><th>Description</th><th>Status</th><th /></tr></thead><tbody>{records.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{editingTier?.id === item.id ? <input className="form-input no-icon" value={editingTier.description || ""} onChange={(e) => setEditingTier({ ...editingTier, description: e.target.value })} /> : item.description || "-"}</td><td>{editingTier?.id === item.id ? <select className="form-select no-icon" value={editingTier.status} onChange={(e) => setEditingTier({ ...editingTier, status: e.target.value })}><option>ACTIVE</option><option>INACTIVE</option></select> : item.status}</td><td>{editingTier?.id === item.id ? <button className="btn-primary" onClick={() => saveTier(editingTier)} disabled={saving}>Save</button> : <button className="icon-button" onClick={() => setEditingTier(item)}><Edit3 size={16} /></button>}</td></tr>)}</tbody></table></section>}
  </main>;
}
