import { useEffect, useState } from "react";
import { useAuth } from "../context/AuthContext";

const API_BASE = "http://localhost:5000/api";

const CheckCircleIcon = ({ size = 14 }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
    <polyline points="22 4 12 14.01 9 11.01" />
  </svg>
);

const LockIcon = ({ size = 15 }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <rect x="3" y="11" width="18" height="11" rx="2" />
    <path d="M7 11V7a5 5 0 0 1 10 0v4" />
  </svg>
);

const AlertCircleIcon = ({ size = 18 }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="12" r="10" />
    <line x1="12" y1="8" x2="12" y2="12" />
    <line x1="12" y1="16" x2="12.01" y2="16" />
  </svg>
);

const ShieldCheckIcon = ({ size = 20 }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
    <path d="m9 12 2 2 4-4" />
  </svg>
);

const DownloadIcon = ({ size = 14 }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
    <polyline points="7 10 12 15 17 10" />
    <line x1="12" y1="15" x2="12" y2="3" />
  </svg>
);

export default function CustomerPortal() {
  const { user, token, logout } = useAuth();
  const [portalData, setPortalData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [acceptedQuotes, setAcceptedQuotes] = useState([]);

  useEffect(() => {
    async function fetchPortal() {
      try {
        const response = await fetch(`${API_BASE}/customer/portal`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const data = await response.json();
        if (!response.ok || !data.success) {
          throw new Error(data.message || "Failed to load customer quotations.");
        }
        setPortalData(data);
      } catch (requestError) {
        setError(requestError.message || "Network error fetching quotation portal.");
      } finally {
        setLoading(false);
      }
    }

    fetchPortal();
  }, [token]);

  const handleAcceptQuote = (quoteId) => {
    setAcceptedQuotes((current) => [...current, quoteId]);
    alert(`Quotation ${quoteId} officially accepted! Your account executive has been notified.`);
  };

  return (
    <main className="main-content">
      <div className="customer-portal-header">
        <div>
          <div className="customer-verified-badge">
            <CheckCircleIcon size={14} /> Verified Customer Account
          </div>
          <h1>{user?.company_name || "Enterprise Customer"} Quotation Portal</h1>
          <p>Authorized contact: <strong>{user?.full_name}</strong> ({user?.email})</p>
        </div>
        <div className="customer-access-summary">
          <div className="customer-access-label">Access Isolation Policy</div>
          <div className="customer-access-value"><LockIcon size={15} /> Strict Single-Tenant Portal</div>
          <button className="btn-secondary" onClick={logout}>Logout</button>
        </div>
      </div>

      {error && (
        <div className="alert alert-danger">
          <AlertCircleIcon />
          <div>{error}</div>
        </div>
      )}

      <div className="customer-security-banner">
        <ShieldCheckIcon size={20} />
        <div>
          <strong>Role Governance Active:</strong> You can view only quotations authored for <strong>{user?.company_name || "your company"}</strong>. Internal sales margins, cost floors, and administrative tools are safeguarded.
        </div>
      </div>

      <div className="data-table-card">
        <div className="customer-quotes-heading">
          <h2>Your Active Quotations</h2>
          <div>Quotes generated by DealFlow360 commercial operations for your organization.</div>
        </div>
        <div style={{ overflowX: "auto" }}>
          <table className="data-table">
            <thead>
              <tr>
                <th>Quote ID</th>
                <th>Package Description</th>
                <th>Valid Until</th>
                <th>Total Value</th>
                <th>Status</th>
                <th style={{ textAlign: "right" }}>Action</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr><td colSpan="6" style={{ textAlign: "center", padding: "3rem", color: "#64748b" }}>Loading customer quotes...</td></tr>
              ) : (portalData?.quotations || []).map((quote) => {
                const isAccepted = acceptedQuotes.includes(quote.id) || quote.status === "Accepted";
                return (
                  <tr key={quote.id}>
                    <td><code>{quote.id}</code></td>
                    <td><strong>{quote.description}</strong></td>
                    <td>{quote.validUntil}</td>
                    <td><strong>{quote.amount}</strong></td>
                    <td><span className={`badge ${isAccepted ? "badge-active" : "badge-pending"}`}>{isAccepted ? "Accepted" : quote.status}</span></td>
                    <td style={{ textAlign: "right", whiteSpace: "nowrap" }}>
                      <div style={{ display: "inline-flex", gap: "0.5rem" }}>
                        <button className="btn-secondary" style={{ padding: "0.4rem 0.75rem", fontSize: "0.8125rem" }} onClick={() => alert(`Downloading signed quotation PDF for ${quote.id}...`)}>
                          <DownloadIcon /> PDF
                        </button>
                        {!isAccepted && (
                          <button className="btn-primary" style={{ width: "auto", padding: "0.4rem 0.85rem", fontSize: "0.8125rem" }} onClick={() => handleAcceptQuote(quote.id)}>
                            <CheckCircleIcon /> Accept Quote
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </main>
  );
}
